### ISSUE TITLE
Use an issue tracker

### ISSUE THREAD

**Issue by plotnick** [ddmcdonald/sparser#1]
Sparser has bugs and issues that should be tracked. GitHub's tracker may or may not be sufficient for our needs; let's see how it works.

**Comment by scoofry** [comment]
We have a Trac page for R3 and CLiC that are already set up.

For CLiC (no tickets yet):
https://svn.sift.info:3333/trac/clic

For R3:
https://svn.sift.info:3333/trac/r3

**Comment by plotnick** [comment]
True, but those are both for specific projects that use Sparser, not for Sparser itself. We could obviously create a TRAC instance for it, but Rusty has had some trouble accessing some SIFT-internal resources in the past (I don't know about those particular ones), and this is where the public git repository ended up, so its tracker seemed worth trying out. It strikes me as somewhat nicer than TRAC so far, but there may be good reasons not to prefer it (e.g., that it's public). I have no strong feelings either way; I just think we should be using something.
