### ISSUE TITLE
comment needs semicolon (?)

### ISSUE THREAD

**Issue by ericpmoss** [ddmcdonald/sparser#2]
Hi,

I think line 257 of Sparser/code/s/init/config/grammars/full-grammar.lisp has a comment that needs a semi-colon:

```
(include-grammar-module  *ambush*) ; 2/21/19 too many fragments                             
                                   ^                                                        
```

**Comment by ddmcdonald** [comment]
You took your update during the small amount of time before this was noticed locally (and fixed).  Made us better disciplined about idiot-testing before committing
